### ISSUE TITLE
Remove the price endpoint

### ISSUE THREAD

**Issue by kristjanmik** [apis-is/docs#6]

**Comment by MiniGod** [comment]
If I'm not mistaken, this is supposed to be in [apis-is/docs-old](https://github.com/apis-is/docs-old)?

**Comment by erlingur** [comment]
Docs still show the price endpoint. Thought I was doing something wrong for a while trying to get it to work.

http://docs.apis.is/#endpoint-price

**Comment by kristjanmik** [comment]
Sorry about that @erlingur. The Krona store api stopped working so we had to remove it. The removal from the docs seems to have mixed up as @MiniGod stated. Can you check this out @benediktvaldez ?

**Comment by erlingur** [comment]
Wow, fast reply @kristjanmik. No problem, just thought I should point this out :)

**Comment by benediktvaldez** [comment]
This is at least not the repo for the currently live documentation, I think.. This version pulls data from the actual running API (well, the beta) and displays endpoints from there.. Well, should, it's 'broken' atm since `XMLHttpRequest cannot load http://beta.apis.is/docs.json. Origin http://docs.beta.apis.is is not allowed by Access-Control-Allow-Origin.` (unrelated issue)

Weird thing is I can't find this anywhere on the [apis-is/docs-old](https://github.com/apis-is/docs-old) repo either (that's the really old one, should that still exist? It's not running anywhere :confused: )..

@kristjanmik where on earth is this stuff? this has become so fragmented that I think we're due for some cleanup..

### I'm officially confused!

![](http://drop.bdvs.info/1jntx/30fVdKqa+)
